### ISSUE TITLE
Can't upload file superior to ~ 2 GO in normal upload

### ISSUE THREAD

**Issue by thorildor** [momo-i/XtraUpload#16]
Hello,

I can't upload file superior to 2 GO in normal upload; in remote upload I understand it's because of the PHP version but it was working with the normal upload in the older version of xraupload I used.

Thanks

**Comment by thorildor** [comment]
Great thanks. So if I find a bug I report it where?

**Comment by momo-i** [comment]
For 3.1.0 branch, since it is not even yet ALPHA release, please report after it has been released. It will be probably released in next month early. For 3.0.0 branch, it is all right here(New Issue) to report bugs.
