### ISSUE TITLE
Installation doesn't work

### ISSUE THREAD

**Issue by NaHoW** [momo-i/XtraUpload#19]
Hello

After uploading and setting the config I get the error "Fatal error: Class 'Xu_hooks_api' not found in /home/nightblue/public_html/application/libraries/Xu_api.php on line 99"
The script did not install yet, I can see the files for the installation but I have no way to access them.

Kind regards,

Simon

**Comment by NaHoW** [comment]
Hello

Thanks for the fast reply. I've always loved this script in the past and I'm am very happy that it is being developped again. If you require any resources let me know.

I had not noticed the requirements and I'm now upgrading my PHP version.

Kind regards,

Simon

**Comment by momo-i** [comment]
OK, first, you must read docs/INSTALL and README.md. Second, from this version(3.0.0), installation is very easy. If your Web server can't use mod_rewrite, you must edit to " $config['index_page'] = 'index.php';" in "application/config/config.php.template". Else, just only put scripts into your web server simply. Finally, go to your web site. By doing so, the installer will run automatically.

P.S.
If you are using the 2.x, and if you want to upgrade to 3.0.0, you can not upgrade to 3.0.0. Please refer to the installation after you create a new database.

**Comment by NaHoW** [comment]
So I've upgraded now
I still have the same error.

You can see here (sorry for the unpro domain name, just for test): http://nightbluesucks.com/

**Comment by momo-i** [comment]
Ohhhhhhhhhhhhhhh, I see. return code was MAC. . . Now fixed. please re-download Xu_hooks_api.php and re-locate.
