### ISSUE TITLE
remote url not work

### ISSUE THREAD

**Issue by maclive** [momo-i/XtraUpload#28]
why remote upload not work

**Comment by momo-i** [comment]
I can't reproduce. In my environment(1), remote upload has been successful. And if you say you can not upload, please tell me your server environment(2) in detail.

1 OS(Fedora 22), Web(Apache 2.6.12), PHP(5.6.12), SQL(Mariadb 10)
2 OS(RHEL 5,6,7, Fedora 20,21,22, Ubuntu, etc..), Web(Apache, Nginx, IIS, etc...), PHP(5.4.xx, 5.6.xx, etc...), SQL(Mysql, Mariadb, etc..), and more...

**Comment by maclive** [comment]
my server centos x64 v 6.5
my sql 5
php 5.5.21
